# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b4f8d44807b0a8eb0deea6842186451e970da56d3445b91c1602eb976b32341802946466eaa9c98a1b65929b9950f22eb2f53fc8bcfe9fa21f59fb35ae674a3

test:
  secret_key_base: d79fcb68836cfbf42a9f48ccc7dba1e3d0373c84125f522af027725bc5de1d72bdfe1f9292b13d7e583e870d8706a5de1891699827121a6bed566ef85f0fd597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
